version: "3.9"

services:
  # 1) Banco SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_produtos
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123
    ports:
      - "1433:1433"
    networks:
      - net_produtos

  # 2) API
  api:
    build:
      context: .           
      dockerfile: Dockerfile.api
    container_name: api_produtos
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=DbProdutos2;User Id=sa;Password=Your_strong_password123;Encrypt=True;TrustServerCertificate=True;
    ports:
      - "8080:80"   
    networks:
      - net_produtos

  # 3) MVC
  mvc:
    build:
      context: .
      dockerfile: Dockerfile.mvc
    container_name: mvc_produtos
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiBaseUrl=http://localhost:8080
    ports:
      - "8081:80"   
    networks:
      - net_produtos

  # 4) Frontend Next.js 
  frontend:
    build:
      context: ./produto-front-nextjs
      dockerfile: ../Dockerfile.nextjs
    container_name: produto-frontend
    ports:
      - "3000:3000"
    networks:
      - net_produtos
    depends_on:
      - api

networks:
  net_produtos:
    driver: bridge
