
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_produtos
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123
    ports:
      - "1433:1433"
    networks:
      - net_produtos

  api:
    build:
      context: .  # Ponto significa que o Dockerfile está na mesma raiz
      dockerfile: Dockerfile
    container_name: api_produtos
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost,1433;Database=DbProdutos2;User Id=sa;Password=Your_strong_password123;Encrypt=True;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    networks:
      - net_produtos

  # Frontend Next.js
  frontend:
    build:
      context: ./produto-front-nextjs
      dockerfile: Dockerfile
    container_name: produto-frontend
    ports:
      - "3000:3000"  # Mapeia a porta 3000 para o frontend Next.js
    networks:
      - net_produtos
    volumes:
      - ./produto-front-nextjs:/app
    depends_on:
      - api

networks:
  net_produtos:
    driver: bridge
